### ISSUE TITLE
speech recognition crashes robot

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/spqrel_tools#22]
@iocchi has seen this a couple of times.

**Comment by andreavanzo** [comment]
I'd need some additional information on how to reproduce the crash or, at least, the log

**Comment by iocchi** [comment]
This is a screenshot I could get when the problem happened

```
[W] 1499714730.460398 5887 qitype.dynamicobject: post on method failed:     ALPythonModule::execute
        calling SpeechRecognition_inst.text_done_callback
<type 'exceptions.RuntimeError'>
        ALAudioRecorder::stopMicrophonesRecording
        Socket Disconnected
[SpeechRecognition] Reset recording..
Traceback (most recent call last):
  File "speech_to_text/speech_recognition.py", line 193, in <module>
    main()
  File "speech_to_text/speech_recognition.py", line 189, in main
    sr.start()
  File "speech_to_text/speech_recognition.py", line 69, in start
    self._spin()
  File "speech_to_text/speech_recognition.py", line 148, in _spin
    self.reset()
  File "speech_to_text/speech_recognition.py", line 137, in reset
    self.audio_recorder.stopMicrophonesRecording()
  File "/opt/aldebaran/lib/python2.7/site-packages/naoqi.py", line 194, in __call__
    return self.__wrapped__.method_missing(self.__method__, *args, **kwargs)
  File "/opt/aldebaran/lib/python2.7/site-packages/naoqi.py", line 264, in method_missing
    raise e
RuntimeError:   ALAudioRecorder::stopMicrophonesRecording
        module destroyed
```

**Comment by andreavanzo** [comment]
It should be solved, but we need some tests to reproduce the behaviour
